
// import Navbar from "../app/components/Navbar"
// import Hero from "../app/components/Hero"

import "../globals.css";
import Footer from "../app/components/Footer"
export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
